// src/components/blog-content.tsx
"use client"

import { RefObject, useEffect, useRef, useState } from "react"
import { PostFilter } from "./post-filter"
import type { Post } from "~/app/nomadsland/types"
import { Badge } from "./ui/badge";
import Link from 'next/link';
import { Card, CardContent } from "./ui/card";
import Image from "next/image";
import { useSearch } from "~/lib/contexts/search-context";
import { useIntersectionObserver } from "~/lib/useIntersectionObserver";

function PostRow({ row, rowIndex }: { row: Post[], rowIndex: number }) {
	const [rowRef, isRowVisible] = useIntersectionObserver();

	return (
		<div
			ref={rowRef as RefObject<HTMLDivElement>}
			className={`
				grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-16 mb-16
				opacity-0 translate-y-8 transition-all duration-[1500ms] ease-in-out
				${isRowVisible ? 'opacity-100 translate-y-0' : ''}
			`}
			style={{ transitionDelay: `${rowIndex * 200}ms` }}
		>
			{row.map((post, index) => (
				<div
					key={post.title}
					className={`${index % 2 === 1 ? 'md:mt-24' : ''}`}
				>
					<PostCard post={post} showDescription={(rowIndex * 2 + index) % 4 === 0} />
				</div>
			))}
		</div>
	);
}

function Posts({ posts }: { posts: Post[] }) {
	if (posts.length === 0) {
		return (
			<div className="py-16 sm:py-24">
				<div className="mx-auto px-6 lg:px-8">
					<div className="text-center py-12">
						<h3 className="text-xl lg:text-2xl font-semibold mb-2">No posts available yet</h3>
						<p className='text-lg lg:text-xl'>Please check back later for new content!</p>
					</div>
				</div>
			</div>
		);
	}

	// Group posts into rows of 2 for desktop view
	const rows = [];
	for (let i = 0; i < posts.length; i += 2) {
		rows.push(posts.slice(i, i + 2));
	}

	return (
		<div className="py-16 sm:py-24">
			<div className="mx-auto px-6 lg:px-8">
				{rows.map((row, rowIndex) => (
					<PostRow key={`row-${rowIndex}`} row={row} rowIndex={rowIndex} />
				))}
			</div>
		</div>
	);
}

function PostCard({ post, showDescription = false }: { post: Post, showDescription?: boolean }) {
	return (
		<Card className="overflow-hidden transition-transform duration-300 bg-transparent border-none shadow-none rounded-none">
			<Link href={`/nomadsland/${post.file}`}>
				<div className="relative aspect-video w-full">
					<Image
						src={post.imageUrl}
						alt={post.title}
						fill
						className="object-contain"
						placeholder="blur"
						blurDataURL="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiPjxyZWN0IHdpZHRoPSIxMDAlIiBoZWlnaHQ9IjEwMCUiIGZpbGw9IiNmZmZmZmYiPjwvcmVjdD48L3N2Zz4="
					/>
				</div>
				<CardContent className="pt-4">
					<div className='inline-flex items-center gap-x-4'>
						{post.categories.map((category, index) => (
							<Badge key={index} variant={'ghost'} className='lowercase text-sm text-brand-white hover:text-white'>
								{category}
							</Badge>
						))}
					</div>
					<h3 className="mb-2 text-xl leading-6 text-brand-white group-hover:text-cold-ivory">
						{post.title}
					</h3>
					{post.author && (
						<p className="text-sm text-brand-white group-hover:text-cold-ivory">
							By {post.author.name}
						</p>
					)}
					{showDescription && (
						<p className="text-base text-brand-white group-hover:text-cold-ivory mt-2 font-spectral font-normal">
							{post.description}
						</p>
					)}
				</CardContent>
			</Link>
		</Card>
	);
}

export function FilteredBlogContent({ posts }: { posts: Post[] }) {
	const [selectedCategories, setSelectedCategories] = useState<string[]>([]);
	const { searchQuery } = useSearch();

	// Filter posts based on both category and search query
	const filteredPosts = posts.filter((post) => {
		// Check if post matches selected categories (if any are selected)
		const matchesCategory = selectedCategories.length === 0 ||
			post.categories.some(category => selectedCategories.includes(category));

		// Check if post matches search query (if there is one)
		const matchesSearch = !searchQuery ||
			post.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
			post.description.toLowerCase().includes(searchQuery.toLowerCase());

		// Post must match both conditions
		return matchesCategory && matchesSearch;
	})
		// Sort posts by date, most recent first
		.sort((a, b) => {
			if (a.date && b.date) {
				return new Date(b.date).getTime() - new Date(a.date).getTime();
			}
			return 0;
		});

	return (
		<>
			<div className='text-center'>
				<h1 className='mb-8 uppercase'>Nomad's <span className="italic">L</span>and</h1>

				<div className="flex flex-col md:flex-row items-center md:justify-center my-6 mx-auto space-x-6">
					<PostFilter
						posts={posts}
						onCategorySelect={setSelectedCategories}
						selectedCategories={selectedCategories}
					/>
				</div>
			</div>
			<div className='grid gap-8'>
				<Posts posts={filteredPosts} />
			</div>
		</>
	);
}

// ui/src/lib/components/blog-content.svelte
<script lang="ts">
	import { Badge } from "$lib/components/ui/badge";
	import { Card, CardContent } from "$lib/components/ui/card";
	import type { Post } from "$lib/schemas/post";

	let {
		posts,
	}: {
		posts: Post[];
	} = $props();

	let selectedCategories = $state<string[]>([]);
	let searchQuery = $state("");

	let allCategories = $derived(
		[...new Set(posts.flatMap((p) => p.categories))].sort(),
	);

	let filteredPosts = $derived(
		posts
			.filter((post) => {
				const matchesCategory =
					selectedCategories.length === 0 ||
					post.categories.some((c) => selectedCategories.includes(c));

				const matchesSearch =
					!searchQuery ||
					post.title
						.toLowerCase()
						.includes(searchQuery.toLowerCase()) ||
					post.description
						.toLowerCase()
						.includes(searchQuery.toLowerCase());

				return matchesCategory && matchesSearch;
			})
			.sort((a, b) => {
				if (a.datetime && b.datetime) {
					return (
						new Date(b.datetime).getTime() -
						new Date(a.datetime).getTime()
					);
				}
				return 0;
			}),
	);

	let rows = $derived.by(() => {
		const result: Post[][] = [];
		for (let i = 0; i < filteredPosts.length; i += 2) {
			result.push(filteredPosts.slice(i, i + 2));
		}
		return result;
	});

	function toggleCategory(category: string) {
		if (selectedCategories.includes(category)) {
			selectedCategories = selectedCategories.filter(
				(c) => c !== category,
			);
		} else {
			selectedCategories = [...selectedCategories, category];
		}
	}

	function observeRow(node: HTMLElement) {
		const observer = new IntersectionObserver(
			([entry]) => {
				if (entry.isIntersecting) {
					node.classList.add("opacity-100", "translate-y-0");
					node.classList.remove("opacity-0", "translate-y-8");
					observer.unobserve(node);
				}
			},
			{ threshold: 0.1 },
		);
		observer.observe(node);
		return {
			destroy() {
				observer.disconnect();
			},
		};
	}

	export function setSearchQuery(query: string) {
		searchQuery = query;
	}
</script>

<div class="text-center">
	<h1 class="mb-8 uppercase">Nomad's <span class="italic">L</span>and</h1>

	<!-- Category filters -->
	<div
		class="flex flex-col md:flex-row items-center md:justify-center my-6 mx-auto space-x-6"
	>
		<div class="flex flex-wrap gap-2 justify-center">
			{#each allCategories as category (category)}
				<button
					class="px-4 py-1.5 rounded-full text-sm font-medium uppercase font-source-code-pro border transition-colors {selectedCategories.includes(
						category,
					)
						? 'bg-brand-white text-black border-brand-white'
						: 'bg-transparent text-brand-white border-brand-white/50 hover:border-brand-white'}"
					onclick={() => toggleCategory(category)}
				>
					{category}
				</button>
			{/each}
			{#if selectedCategories.length > 0}
				<button
					class="px-4 py-1.5 rounded-full text-sm font-medium uppercase font-source-code-pro text-brand-white/70 hover:text-brand-white transition-colors"
					onclick={() => (selectedCategories = [])}
				>
					Clear filters
				</button>
			{/if}
		</div>
	</div>
</div>

<div class="grid gap-8">
	{#if filteredPosts.length === 0}
		<div class="py-16 sm:py-24">
			<div class="mx-auto px-6 lg:px-8">
				<div class="text-center py-12">
					<h3 class="text-xl lg:text-2xl font-semibold mb-2">
						No posts available yet
					</h3>
					<p class="text-lg lg:text-xl">
						Please check back later for new content!
					</p>
				</div>
			</div>
		</div>
	{:else}
		<div class="py-16 sm:py-24">
			<div class="mx-auto px-6 lg:px-8">
				{#each rows as row, rowIndex (rowIndex)}
					<div
						use:observeRow
						class="grid grid-cols-1 md:grid-cols-2 gap-x-12 gap-y-16 mb-16 opacity-0 translate-y-8 transition-all duration-[1500ms] ease-in-out"
						style:transition-delay="{rowIndex * 200}ms"
					>
						{#each row as post, index (post.title)}
							<div class={index % 2 === 1 ? "md:mt-24" : ""}>
								<Card
									class="overflow-hidden transition-transform duration-300 bg-transparent border-none shadow-none rounded-none ring-0"
								>
									<a href="/nomadsland/{post.file}">
										<div
											class="relative aspect-video w-full"
										>
											<img
												src={post.imageUrl}
												alt={post.title}
												class="object-contain w-full h-full"
												loading="lazy"
											/>
										</div>
										<CardContent class="pt-4">
											<div
												class="inline-flex items-center gap-x-4"
											>
												{#each post.categories as category (category)}
													<Badge
														variant="ghost"
														class="lowercase text-sm text-brand-white hover:text-white"
													>
														{category}
													</Badge>
												{/each}
											</div>
											<h3
												class="mb-2 text-xl leading-6 text-brand-white group-hover/card:text-cold-ivory"
											>
												{post.title}
											</h3>
											{#if post.author}
												<p
													class="text-sm text-brand-white group-hover/card:text-cold-ivory"
												>
													By {post.author.name}
												</p>
											{/if}
											{#if (rowIndex * 2 + index) % 4 === 0}
												<p
													class="text-base text-brand-white group-hover/card:text-cold-ivory mt-2 font-spectral font-normal"
												>
													{post.description}
												</p>
											{/if}
										</CardContent>
									</a>
								</Card>
							</div>
						{/each}
					</div>
				{/each}
			</div>
		</div>
	{/if}
</div>
