// src/components/ui/infinite-moving-cards.tsx
import React, { useEffect, useState } from 'react';
import { cn } from '~/lib/utils';
import { Image } from './image';

export type MovingCardProps = {
	name: string;
	image: string;
	link: string;
	quote?: string;
}

export const InfiniteMovingCards = ({
	items,
	direction = 'left',
	speed = 'fast',
	pauseOnHover = false,
	className,
}: {
	items: MovingCardProps[];
	direction?: 'left' | 'right';
	speed?: 'fast' | 'normal' | 'slow';
	pauseOnHover?: boolean;
	className?: string;
}) => {
	const containerRef = React.useRef<HTMLDivElement>(null);
	const scrollerRef = React.useRef<HTMLUListElement>(null);

	useEffect(() => {
		addAnimation();
	}, []);
	const [start, setStart] = useState(false);
	function addAnimation() {
		if (containerRef.current && scrollerRef.current) {
			const scrollerContent = Array.from(scrollerRef.current.children);

			scrollerContent.forEach((item) => {
				const duplicatedItem = item.cloneNode(true);
				if (scrollerRef.current) {
					scrollerRef.current.appendChild(duplicatedItem);
				}
			});

			getDirection();
			getSpeed();
			setStart(true);
		}
	}
	const getDirection = () => {
		if (containerRef.current) {
			if (direction === 'left') {
				containerRef.current.style.setProperty(
					'--animation-direction',
					'forwards'
				);
			} else {
				containerRef.current.style.setProperty(
					'--animation-direction',
					'reverse'
				);
			}
		}
	};
	const getSpeed = () => {
		if (containerRef.current) {
			if (speed === 'fast') {
				containerRef.current.style.setProperty('--animation-duration', '20s');
			} else if (speed === 'normal') {
				containerRef.current.style.setProperty('--animation-duration', '40s');
			} else {
				containerRef.current.style.setProperty('--animation-duration', '80s');
			}
		}
	};
	return (
		<div
			ref={containerRef}
			className={cn(
				'scroller relative z-20 max-w-7xl overflow-hidden [mask-image:linear-gradient(to_right,transparent,white_20%,white_80%,transparent)]',
				className
			)}
		>
			<ul
				ref={scrollerRef}
				className={cn(
					'flex w-max min-w-full shrink-0 flex-nowrap py-4',
					start && 'animate-scroll',
					pauseOnHover && 'hover:[animation-play-state:paused]'
				)}
			>
				{items.map((item, idx) => (
					<li
						className='relative md:w-[300px] w-[220px] max-w-full shrink-0 rounded-2xl md:px-8 px-3 md:py-6 py-4'
						key={item.name}
					>
						{/* <Link
							href={item.link}
							className='text-sm underline deocration-dotted underline-offset-2'
							target='_blank'
							rel='noopener noreferrer'
						>
							<span className='absolute inset-0'></span>
						</Link> */}
						<blockquote>
							<div
								aria-hidden='true'
								className='user-select-none pointer-events-none absolute -top-0.5 -left-0.5 -z-1 h-[calc(100%_+_4px)] w-[calc(100%_+_4px)]'
							></div>

							<div className='relative w-full md:h-40 h-32 mb-4 overflow-hidden rounded-lg flex place-items-center aspect-[4/3]'>
								<Image
									src={item.image}
									alt={`Image for ${item.name}`}
									className='object-cover object-center mx-auto'
									width={125}
									height={100}
									loading='eager'
								/>
							</div>
							{/* <span className='relative z-20 text-sm leading-[1.6] font-normal'>
								{item.quote}
							</span>
							<div className='relative z-20 mt-6 flex flex-row items-center'>
								<span className='flex flex-col gap-1'>
									<span className='text-sm leading-[1.6] font-normal text-secondary-foreground/80'>
										{item.name}
									</span>
								</span>
							</div> */}
						</blockquote>
					</li>
				))}
			</ul>
		</div>
	);
};

// ui/src/lib/components/infinite-moving-cards.svelte
<script lang="ts">
	import { onMount } from "svelte";

	export type MovingCardProps = {
		name: string;
		image: string;
		link: string;
		quote?: string;
	};

	let {
		items,
		direction = "left",
		speed = "fast",
		pauseOnHover = false,
		class: className = "",
	}: {
		items: MovingCardProps[];
		direction?: "left" | "right";
		speed?: "fast" | "normal" | "slow";
		pauseOnHover?: boolean;
		class?: string;
	} = $props();

	let containerEl: HTMLDivElement | undefined = $state();
	let scrollerEl: HTMLUListElement | undefined = $state();
	let started = $state(false);

	function getAnimationDuration(speed: string): string {
		switch (speed) {
			case "fast":
				return "20s";
			case "normal":
				return "40s";
			default:
				return "80s";
		}
	}

	function getAnimationDirection(direction: string): string {
		return direction === "left" ? "forwards" : "reverse";
	}

	onMount(() => {
		if (containerEl && scrollerEl) {
			// Duplicate items for infinite scroll effect
			const scrollerContent = Array.from(scrollerEl.children);
			scrollerContent.forEach((item) => {
				const duplicatedItem = item.cloneNode(true);
				scrollerEl!.appendChild(duplicatedItem);
			});

			containerEl.style.setProperty(
				"--animation-direction",
				getAnimationDirection(direction),
			);
			containerEl.style.setProperty(
				"--animation-duration",
				getAnimationDuration(speed),
			);
			started = true;
		}
	});
</script>

<div
	bind:this={containerEl}
	class={[
		"scroller relative z-20 max-w-7xl overflow-hidden mask-[linear-gradient(to_right,transparent,white_20%,white_80%,transparent)]",
		className,
	]}
>
	<ul
		bind:this={scrollerEl}
		class={[
			"flex w-max min-w-full shrink-0 flex-nowrap py-4",
			started && "animate-scroll",
			pauseOnHover && "hover:[animation-play-state:paused]",
		]}
	>
		{#each items as item (item.name)}
			<li
				class="relative md:w-[300px] w-[220px] max-w-full shrink-0 rounded-2xl md:px-8 px-3 md:py-6 py-4"
			>
				<blockquote>
					<div
						aria-hidden="true"
						class="user-select-none pointer-events-none absolute -top-0.5 -left-0.5 -z-1 h-[calc(100%+4px)] w-[calc(100%+4px)]"
					></div>

					<div
						class="relative w-full md:h-40 h-32 mb-4 overflow-hidden rounded-lg flex place-items-center aspect-4/3"
					>
						<img
							src={item.image}
							alt="Image for {item.name}"
							class="object-cover object-center mx-auto"
							width="125"
							height="100"
							loading="lazy"
						/>
					</div>
				</blockquote>
			</li>
		{/each}
	</ul>
</div>
