// ui/src/lib/components/navbar.svelte
<script module lang="ts">
	export type NavItem = {
		label: string;
		href: string;
	};
</script>

<script lang="ts">
	import { MenuIcon, ShoppingCart } from "@lucide/svelte";
	import { Button } from "$lib/components/ui/button";
	import * as Sheet from "$lib/components/ui/sheet";
	import { cn, generateSrcSet } from "$lib/utils";
	import { page } from "$app/state";
	import { trackEvent } from "$lib/analytics.svelte";
	import SearchBar from "./search-bar.svelte";
	import { getCart } from "$lib/context/cart.svelte";

	const cart = getCart();

	export const navLinks: NavItem[] = [
		{ label: "Home", href: "/" },
		{ label: "Our Story", href: "/about" },
		{
			label: "Book a Treatment",
			href: "https://app.squareup.com/appointments/book/augj56g525h4rw/LSP68REJT9SVH/start",
		},
		{ label: "Shop", href: "/shop" },
		{
			label: "Gift Card",
			href: "https://app.squareup.com/gift/ML665NPQYDHTJ/order",
		},
		{ label: "Nomad's Land", href: "/nomadsland" },
	];

	const isExternal = (url: string) =>
		url.startsWith("http://") || url.startsWith("https://");

	function trackClick(label: string) {
		if (label === "Gift Card") {
			trackEvent("Clicked Gift Card");
		} else if (label === "Book a Treatment") {
			trackEvent("Clicked Treatment Booking");
		} else if (label === "Shop") {
			trackEvent("Clicked Shop");
		}
	}

	let isDesktopMenuOpen = $state(false);

	let pathname = $derived(page.url.pathname);
	let isLightPage = $derived(pathname === "/" || pathname === "/nomadsland");
</script>

<header
	class="flex items-center justify-between absolute top-0 w-full bg-transparent p-4 md:p-6 z-1"
>
	<div class="flex items-center">
		<!-- Mobile menu -->
		<Sheet.Root>
			<Sheet.Trigger>
				{#snippet child({ props })}
					<Button
						variant="ghost"
						class="self-start w-auto h-fit md:hidden"
						{...props}
					>
						<MenuIcon
							class={cn(
								"size-6! lg:size-8! xl:size-10! text-black hover:cursor-pointer",
								{
									"text-brand-white": isLightPage,
								},
							)}
							strokeWidth={2.5}
						/>
					</Button>
				{/snippet}
			</Sheet.Trigger>
			<Sheet.Content
				side="left"
				class="md:hidden shadow-none bg-black text-white border-none pl-4"
			>
				<Sheet.Header>
					<Sheet.Title class="sr-only">Navigation Menu</Sheet.Title>
				</Sheet.Header>
				<nav class="flex flex-col gap-4 mt-8">
					{#each navLinks as item (item.label)}
						<a
							href={item.href}
							rel="nofollow noopener noreferrer"
							target={isExternal(item.href)
								? "_blank"
								: undefined}
							class="font-source-code-pro uppercase text-lg"
							onclick={() => trackClick(item.label)}
						>
							{item.label}
						</a>
					{/each}
				</nav>
			</Sheet.Content>
		</Sheet.Root>

		<!-- Desktop menu toggle -->
		<Button
			variant="ghost"
			class="hidden md:flex self-start w-auto h-fit hover:cursor-pointer hover:bg-transparent"
			onclick={() => (isDesktopMenuOpen = !isDesktopMenuOpen)}
		>
			<!-- {#if isDesktopMenuOpen}
				<MenuIcon
					class={cn(
						"!size-6 lg:!size-8 xl:!size-10 text-black -rotate-90",
						{
							"text-brand-white": isLightPage,
						},
					)}
					strokeWidth={2.5}
				/>
			{:else}
				<MenuIcon
					class={cn("!size-6 lg:!size-8 xl:!size-10 text-black", {
						"text-brand-white": isLightPage,
					})}
					strokeWidth={2.5}
				/>
			{/if} -->
			<MenuIcon
				class={cn("size-6! lg:size-8! xl:size-10! text-black", {
					"text-brand-white": isLightPage,
				})}
				strokeWidth={2.5}
			/>
		</Button>

		<!-- Desktop navigation -->
		<nav
			class={cn("hidden md:flex ml-8", {
				"md:hidden": !isDesktopMenuOpen,
			})}
		>
			<ul
				class={cn("flex gap-8 *:uppercase text-black", {
					"text-brand-white": isLightPage,
				})}
			>
				{#each navLinks as item (item.label)}
					<li
						class="motion-safe:hover:underline motion-safe:hover:underline-offset-2 duration-300 ease-in-out"
					>
						<a
							href={item.href}
							class={cn(
								"font-semibold text-lg font-source-code-pro no-underline",
								{
									"text-brand-white": isLightPage,
								},
							)}
							rel="nofollow noopener noreferrer"
							target={isExternal(item.href)
								? "_blank"
								: undefined}
							onclick={() => {
								trackClick(item.label);
								isDesktopMenuOpen = false;
							}}
						>
							{item.label}
						</a>
					</li>
				{/each}
			</ul>
		</nav>
	</div>

	<div class="flex max-w-[500px] w-auto items-center justify-end">
		{#if pathname === "/shop"}
			<Button onclick={() => cart.toggle()} variant="outline">
				Cart ({cart.items.length})
			</Button>
		{/if}
		{#if pathname === "/nomadsland"}
			<div class="flex items-center mr-2"><SearchBar /></div>
			<Button
				variant="ghost"
				class="hidden sm:inline-flex text-brand-white hover:text-white hover:bg-black rounded-full hover:cursor-pointer font-source-code-pro"
				href="#subscription-form"
			>
				Get Our Newsletter
			</Button>
		{:else if pathname === "/"}
			<a href="/" class="no-underline block">
				<img
					src="https://blue-nomad.nyc3.cdn.digitaloceanspaces.com/logos/blue-nomad-light.png"
					srcset={generateSrcSet(
						"https://blue-nomad.nyc3.cdn.digitaloceanspaces.com/logos/blue-nomad-light.png",
						[400, 800, 1200, 1600],
						"webp",
						85,
					)}
					alt="Blue Nomad Logo"
					class="w-full h-auto sm:max-w-[300px]"
					sizes="(max-width: 640px) 100vw, (max-width: 1024px) 70vw, (max-width: 1280px) 50vw, 33vw"
				/>
			</a>
		{/if}
	</div>
</header>

// src/components/navbar.tsx
"use client"

import { MenuIcon as Menu } from 'lucide-react';
import Link from 'next/link';
import React from 'react';
import Image from 'next/image';
import { Button } from './ui/button';
import {
	Sheet,
	SheetContent,
	SheetTrigger,
	SheetTitle,
} from './ui/sheet';
import { usePathname } from 'next/navigation';
import { cn } from '~/lib/utils';
import { useViewport } from '~/lib/useViewport';
import { SearchBar } from './search-bar';
import { useSearch } from '~/lib/contexts/search-context';
import { usePlausible } from 'next-plausible';

export type NavItem = {
	label: string;
	href: string;
};

export const navLinks: NavItem[] = [
	{
		label: 'Home',
		href: '/',
	},
	{
		label: 'Our Story',
		href: '/about',
	},
	{
		label: 'Book a Treatment',
		href: 'https://app.squareup.com/appointments/book/augj56g525h4rw/LSP68REJT9SVH/start',
		// href: '/booking'
	},
	{
		label: 'Gift Card',
		href: 'https://app.squareup.com/gift/ML665NPQYDHTJ/order',
	},
	{
		label: "Nomad's Land",
		href: '/nomadsland',
	},
];

export const Navbar: React.FC = () => {
	const pathname = usePathname();
	const plausible = usePlausible();
	const { width } = useViewport();
	const { setSearchQuery } = useSearch(); // Use our search context

	// Handle search query changes
	const handleSearch = (query: string) => {
		setSearchQuery(query);
	};

	return (
		<header
			className={
				'flex items-center justify-between absolute top-0 w-full bg-transparent p-4 md:p-6 z-1'
			}
		>
			<div className='flex items-center group'>
				<Sheet>
					<SheetTrigger asChild>
						<Button variant={'ghost'} className='self-start w-auto h-fit'>
							<Menu
								className={cn('!size-6 lg:!size-8 xl:!size-10 text-black hover:cursor-pointer', {
									'text-brand-white': pathname === '/' || pathname === '/nomadsland'
								})}
								strokeWidth={2.5}
							/>
						</Button>
					</SheetTrigger>
					<SheetContent
						side="left"
						className='md:hidden shadow-none bg-black text-white border-none pl-4'
					>
						<SheetTitle className="sr-only">Navigation Menu</SheetTitle>
						<nav className="flex flex-col gap-4 mt-8">
							{navLinks.map((item) => (
								<Link
									key={item.label}
									href={item.href}
									rel='nofollow noopener noreferrer'
									target={item.href.includes('squareup') ? '_blank' : undefined}
									className='font-source-code-pro uppercase text-lg'
									onClick={() => {
										if (item.label === 'Gift Card') {
											plausible('Clicked Gift Card')
										} else if (item.label === 'Book a Treatment') {
											plausible('Clicked Treatment Booking')
										}
									}}
								>
									{item.label}
								</Link>
							))}
						</nav>
					</SheetContent>
				</Sheet>
				<nav className='hidden group-hover:flex'>
					<ul
						className={cn('flex gap-8 *:uppercase text-black', {
							'text-brand-white': pathname === '/' || pathname === '/nomadsland'
						})}
					>
						{navLinks.map((item) => (
							<li
								key={item.label}
								className='motion-safe:hover:underline motion-safe:hover:underline-offset-2 duration-300 ease-in-out'
							>
								<Link
									href={item.href}
									className={cn('font-semibold text-lg font-source-code-pro no-underline', {
										'text-brand-white': pathname === '/' || pathname === '/nomadsland'
									})}
									rel='nofollow noopener noreferrer'
									target={item.href.includes('squareup') ? '_blank' : undefined}
								>
									{item.label}
								</Link>
							</li>
						))}
					</ul>
				</nav>
			</div>

			<div className='flex max-w-[500px] w-auto items-center justify-end'>
				{pathname === '/nomadsland' && (
					<>
						<div className="flex items-center mr-2">
							<SearchBar onSearch={handleSearch} />
						</div>
						<Button variant={'ghost'} className={'hidden sm:inline-flex text-brand-white hover:text-white hover:bg-black rounded-full hover:cursor-pointer'}>
							{/* <Link href="#subscription-form" target='_blank' rel='noopener noreferrer' className='no-underline'>
								Get Our Newsletter
							</Link> */}
							<Link href="#subscription-form" className='no-underline'>
								Get Our Newsletter
							</Link>
						</Button>
					</>
				)}
				{pathname !== '/nomadsland' && (
					<Link
						href='/'
						className={cn('no-underline', {
							'block': pathname === '/',
							'hidden': pathname !== '/'
						})}
					>
						<Image
							// src={pathname === '/' ? (width < 768 ? 'https://blue-nomad.nyc3.cdn.digitaloceanspaces.com/logos/blue-nomad.png' : 'https://blue-nomad.nyc3.cdn.digitaloceanspaces.com/logos/blue-nomad-light.png') : 'https://blue-nomad.nyc3.cdn.digitaloceanspaces.com/logos/blue-nomad.png'}
							src={'https://blue-nomad.nyc3.cdn.digitaloceanspaces.com/logos/blue-nomad-light.png'}
							alt='Blue Nomad Logo'
							width={0}
							height={0}
							sizes='(max-width: 768px) 300px, (max-width: 1024px) 300px, 400px'
							priority
							className='w-full h-auto sm:max-w-[300px]'
						/>
					</Link>
				)}
			</div>
		</header>
	);

};
